config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index", as: :home
  get "home/create_session"
  resources :employees
  resources :skills
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees, dependent: :nullify
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy!

    respond_to do |format|
      format.html { redirect_to departments_path, status: :see_other, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :description)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]
  before_action :set_departments, only: %i[ new create edit update ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @departments = Department.all
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_path, status: :see_other, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def set_departments
      @departments = Department.all
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :birthdate, :is_active, :is_manager, :department_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @employees = Employee.all
    @skills = Skill.all
  end

  def create_session
    session[:user] = params[:user]
    redirect_to root_path
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: %i[ show edit update destroy ]

  # GET /skills or /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1 or /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills or /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: "Skill was successfully created." }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1 or /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: "Skill was successfully updated." }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1 or /skills/1.json
  def destroy
    @skill.destroy!

    respond_to do |format|
      format.html { redirect_to skills_path, status: :see_other, notice: "Skill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.require(:skill).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= department.description %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<% content_for :title, "Editing department" %>

<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department %> |
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Departments" %>

<h1>Departments</h1>

<div id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
    <p>
      <%= link_to "Show this department", department %>
    </p>
  <% end %>
</div>

<%= link_to "New department", new_department_path %>

app/views/departments/new.html.erb
<% content_for :title, "New department" %>

<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>

  <%= button_to "Destroy this department", @department, method: :delete %>
</div>

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <h2><%= employee.first_name %> <%= employee.last_name %></h2>

  <p>
    <strong>
    <%= employee.department.name %>
    </strong>
  </p>

  <p>
    <strong>Birthdate:</strong>
    <%= employee.birthdate&.strftime('%D') %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= employee.is_active %> 
    <strong>Manager:</strong>
    <%= employee.is_manager %>
  </p>
</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :birthdate, style: "display: block" %>
    <%= form.date_field :birthdate %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.label :is_manager, style: "display: block" %>
    <%= form.check_box :is_manager %>
  </div>

  <div>
    <%= form.label :department_id, style: "display: block" %>
    <%= form.collection_select :department_id, @departments, :id, :name, prompt: 'Select a Department...' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<% content_for :title, "Editing employee" %>

<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Employees" %>

<h1>Employees</h1>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<% content_for :title, "New employee" %>

<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>

app/views/home/index.html.erb
<% content_for :title, "Home" %>
<h1>Welcome to the Sad App</h1>
<p>into text goes here</p>

<hr>
<p><%= session[:user] %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sad App > <%= content_for(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/_form.html.erb
<%= form_with(model: skill) do |form| %>
  <% if skill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/_skill.html.erb
<div id="<%= dom_id skill %>">
  <p>
    <strong>Name:</strong>
    <%= skill.name %>
  </p>

</div>

app/views/skills/edit.html.erb
<% content_for :title, "Editing skill" %>

<h1>Editing skill</h1>

<%= render "form", skill: @skill %>

<br>

<div>
  <%= link_to "Show this skill", @skill %> |
  <%= link_to "Back to skills", skills_path %>
</div>

app/views/skills/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Skills" %>

<h1>Skills</h1>

<div id="skills">
  <% @skills.each do |skill| %>
    <%= render skill %>
    <p>
      <%= link_to "Show this skill", skill %>
    </p>
  <% end %>
</div>

<%= link_to "New skill", new_skill_path %>

app/views/skills/new.html.erb
<% content_for :title, "New skill" %>

<h1>New skill</h1>

<%= render "form", skill: @skill %>

<br>

<div>
  <%= link_to "Back to skills", skills_path %>
</div>

app/views/skills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @skill %>

<div>
  <%= link_to "Edit this skill", edit_skill_path(@skill) %> |
  <%= link_to "Back to skills", skills_path %>

  <%= button_to "Destroy this skill", @skill, method: :delete %>
</div>